# Generated by Django 3.0.8 on 2020-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_to_complete',
            field=models.DateField(),
        ),
    ]
