# Generated by Django 3.0.8 on 2020-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200718_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_to_complete',
            field=models.DateTimeField(),
        ),
    ]
